---
title: "Richard Harris"
subtitle: "School of Geographical Sciences, University of Bristol"
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
#   code_folding: show
    self_contained: true
    thumbnails: false
    lightbox: true
    downcute_theme: "chaos"
pkgdown:
  as_is: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About Me

I am a social geographer interested in socio-spatial inequalities within society and their causes. Presently I am Director of the South West Doctoral Training Partnership and was founding director of the University of Bristol’s £1.3 million funded Q-Step Centre for undergraduate, quantitative social science. My early research looked at the application of spatial statistics, geographic information science and geodemographics in marketing, public policy and urban geography – all examples of what are now described as geographic data science. More recent work has been in urban analytics and cartographic geovisualisation of administrative datasets, focusing on developing and applying innovative computational methods to analyse the geographies of Covid-19, to measure and to visualise spatial scales of social and ethnic segregation, and to study choice and markets in educational systems; and also in the geographies of education, supporting quantitative and statistical literacy amongst geographers and undergraduate and postgraduate social scientists. I am also a licensed lay minister in the Church of England so have some theological interests too.

## Links

XXXX