<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Spatial Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="_spregress_files/libs/clipboard/clipboard.min.js"></script>
<script src="_spregress_files/libs/quarto-html/quarto.js"></script>
<script src="_spregress_files/libs/quarto-html/popper.min.js"></script>
<script src="_spregress_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="_spregress_files/libs/quarto-html/anchor.min.js"></script>
<link href="_spregress_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="_spregress_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="_spregress_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="_spregress_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="_spregress_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Spatial Regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>In the previous session we looked at geographically weighted statistics, including geographically weighted correlation, which examines whether the correlation between two variables varies across a map. In this session we extend from correlation to looking at regression modelling with a spatial component (spatial regression). The data we shall use are a map of the rate of COVID-19 infections per thousand population in neighbourhoods of the North West of England over the period from the week commencing 2020-03-07 to the week commencing 2022-04-16. That rate is calculated as the total number of reported infections per neighbourhood, divided by the <a href="https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/middlesuperoutputareamidyearpopulationestimates" target="blank">mid-2020 ONS estimated population</a>. There are three problems with these data, which originate (prior to adjustment) from <a href="https://coronavirus.data.gov.uk/details/download" target="_blank">https://coronavirus.data.gov.uk/details/download</a>:</p>
<ol type="1">
<li>The rate, as calculated, does not allow for re-infection (i.e.&nbsp;the same person can catch COVID-19 more than once).</li>
<li>Not everyone who had COVID was tested for a positive diagnosis. Limitations in the testing regime are described in <a href="https://link.springer.com/article/10.1007/s12061-021-09400-8" target="_blank">this paper</a> and are most severe earlier in the pandemic and again towards the end of the data period when testing was scaled-back and then largely withdrawn.</li>
<li>For data protection reasons, where a neighbourhood had less than three cases in a week, that number was reported as zero even though it could really be one or two. This undercount adds up, although, unsurprisingly it affects the largest cities most (because they have more neighbourhoods to be undercounted) in weeks when COVID is not especially prevalent (because in other weeks there are more often more than two cases per neighbourhoods). An adjustment has been made to the data to allow for this censoring of the data but not for the undercount caused by not testing positive.</li>
</ol>
<p>Despite their shortcomings, the data are sufficient to illustrate the methods, below.</p>
</section>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">Getting Started</h2>
<p>The data are downloaded as follows. The required packages should be installed already, from previous sessions. As before, you may wish to begin by opening the R Project that you created for these classes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span>(<span class="st">"remotes"</span> <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[,<span class="dv">1</span>])) <span class="fu">install.packages</span>(<span class="st">"remotes"</span>, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span>(<span class="st">"ggsflabel"</span> <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[,<span class="dv">1</span>])) remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"yutannihilation/ggsflabel"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(sf)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(tidyverse)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(ggsflabel)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">file.exists</span>(<span class="st">"covid.geojson"</span>)) <span class="fu">download.file</span>(<span class="st">"https://github.com/profrichharris/profrichharris.github.io/raw/main/MandM/data/covid.geojson"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="st">"covid.geojson"</span>, <span class="at">mode =</span> <span class="st">"wb"</span>, <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">read_sf</span>(<span class="st">"covid.geojson"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(regionName <span class="sc">==</span> <span class="st">"North West"</span>) <span class="ot">-&gt;</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  covid</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Looking at a map of the COVID-19 rates, it appears that there are patches of higher rates that tend to cluster in cities such as Preston, Manchester and Liverpool, although not exclusively so.</p>
<p><img src="hazard.gif" class="img-fluid" width="75"></p>
<p><font size="3">Don’t forget that you can, if you wish, use the <code>cols4all</code> and it’s functions, e.g.&nbsp;<code>scale_fill_continuous_c4a_seq()</code> instead of <code>scale_fill_distiller()</code> in the code chunk below.</font></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>covid <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Rate <span class="sc">&gt;</span> <span class="dv">400</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(LtlaName) <span class="sc">|&gt;</span>   <span class="co"># LtlaName is the name of the local authority</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">duplicated</span>(LtlaName)) <span class="ot">-&gt;</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  high_rate</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> covid, <span class="fu">aes</span>(<span class="at">fill =</span> Rate), <span class="at">size =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"YlOrRd"</span>, <span class="at">direction =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf_label_repel</span>(<span class="at">data =</span> high_rate, <span class="fu">aes</span>(<span class="at">label =</span> LtlaName), <span class="at">size =</span> <span class="dv">3</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>                      <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>… and not without variation within the cities such as Manchester:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> covid <span class="sc">|&gt;</span> <span class="fu">filter</span>(LtlaName <span class="sc">==</span> <span class="st">"Manchester"</span>)) <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> Rate), <span class="at">size =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"YlOrRd"</span>, <span class="at">direction =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Across the map there appears to be a pattern of positive spatial autocorrelation in the COVID-19 rates of contiguous neighbours, whether this is measured using a Moran test,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(spdep)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>spweight <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(<span class="fu">poly2nb</span>(covid, <span class="at">snap =</span> <span class="dv">1</span>))</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.test</span>(covid<span class="sc">$</span>Rate, spweight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  covid$Rate  
weights: spweight    

Moran I statistic standard deviate = 24.422, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
     0.4919206758     -0.0010834236      0.0004075223 </code></pre>
</div>
</div>
<p>or using the Pearson correlation,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="fu">lag.listw</span>(spweight, covid<span class="sc">$</span>Rate), covid<span class="sc">$</span>Rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6726405</code></pre>
</div>
</div>
<p>Some of the ‘hot spots’ of infection are suggested using the geographically-weighted means,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(GWmodel)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>covid_sp <span class="ot">&lt;-</span> <span class="fu">as_Spatial</span>(covid)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(Rate <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> covid_sp,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">adaptive =</span> <span class="cn">TRUE</span>, <span class="at">kernel =</span> <span class="st">"bisquare"</span>, <span class="at">longlat =</span> F)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>gwstats <span class="ot">&lt;-</span> <span class="fu">gwss</span>(covid_sp, <span class="at">vars =</span> <span class="st">"Rate"</span>, <span class="at">bw =</span> bw, <span class="at">kernel =</span> <span class="st">"bisquare"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">adaptive =</span> <span class="cn">TRUE</span>, <span class="at">longlat =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Plotting these,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>covid<span class="sc">$</span>Rate_LM <span class="ot">&lt;-</span> gwstats<span class="sc">$</span>SDF<span class="sc">$</span>Rate_LM</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(covid, <span class="fu">aes</span>(<span class="at">fill =</span> Rate_LM)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">size =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"YlOrRd"</span>, <span class="at">direction =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>They also are suggested using the G-statistic with a somewhat arbitrary bandwidth of 5km.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_centroid</span>(covid, <span class="at">of_largest_polygon =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>neighbours <span class="ot">&lt;-</span> <span class="fu">dnearneigh</span>(coords, <span class="dv">0</span>, <span class="dv">5000</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>spweightB <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(neighbours, <span class="at">style =</span> <span class="st">"B"</span>, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>covid<span class="sc">$</span>localG <span class="ot">&lt;-</span> <span class="fu">localG</span>(covid<span class="sc">$</span>Rate, spweightB)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>brks <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">min</span>(covid<span class="sc">$</span>localG, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>          <span class="sc">-</span><span class="fl">3.29</span>, <span class="sc">-</span><span class="fl">2.58</span>, <span class="sc">-</span><span class="fl">1.96</span>, <span class="fl">1.96</span>, <span class="fl">2.58</span>, <span class="fl">3.29</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>          <span class="fu">max</span>(covid<span class="sc">$</span>localG, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>covid<span class="sc">$</span>localG_gp <span class="ot">&lt;-</span> <span class="fu">cut</span>(covid<span class="sc">$</span>localG, brks, <span class="at">include.lowest =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>pal <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"purple"</span>, <span class="st">"dark blue"</span>, <span class="st">"light blue"</span>, <span class="st">"light grey"</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"yellow"</span>, <span class="st">"orange"</span>, <span class="st">"red"</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(covid, <span class="fu">aes</span>(<span class="at">fill =</span> localG_gp)) <span class="sc">+</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">size =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="st">"G"</span>, <span class="at">values =</span> pal, <span class="at">na.value =</span> <span class="st">"white"</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>                    <span class="at">na.translate =</span> F) <span class="sc">+</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_legend</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="an-initial-model-to-explain-the-spatial-patterns-in-the-covid-19-rates" class="level2">
<h2 class="anchored" data-anchor-id="an-initial-model-to-explain-the-spatial-patterns-in-the-covid-19-rates">An initial model to explain the spatial patterns in the COVID-19 rates</h2>
<p>It is likely that the spatial variation in the COVID-19 rates is due to differences in the physical attributes of the different neighbourhoods and/or of the populations who live in them. For example, the rates may be related to the relative level of deprivation in the neighbourhoods (the <a href="https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019" target="_blank">Index of Multiple Deprivation</a>, <code>IMD</code>), the age composition of their populations (e.g.&nbsp;percentage aged 0 to 11, <code>age0.11</code>), the population density (<code>density</code>), the number of carehome beds (<code>carebeds</code>, because particularly early on in the pandemic, carehome residents were at very high risk), and whether they contain an Accident and Emergency hospital (<code>AandE</code>, coded 1 if they do and 0 if they don’t). Incorporating this into a standard regression model gives,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>ols1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Rate <span class="sc">~</span> IMD <span class="sc">+</span> age0<span class="fl">.11</span> <span class="sc">+</span> age12<span class="fl">.17</span> <span class="sc">+</span> age18<span class="fl">.24</span> <span class="sc">+</span> age25<span class="fl">.34</span> <span class="sc">+</span> age35<span class="fl">.39</span> <span class="sc">+</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>             age50<span class="fl">.59</span> <span class="sc">+</span> age60<span class="fl">.69</span> <span class="sc">+</span> age70plus <span class="sc">+</span> density <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>             carebeds <span class="sc">+</span> AandE, <span class="at">data =</span> covid)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ols1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Rate ~ IMD + age0.11 + age12.17 + age18.24 + age25.34 + 
    age35.39 + age50.59 + age60.69 + age70plus + density + carebeds + 
    AandE, data = covid)

Residuals:
     Min       1Q   Median       3Q      Max 
-134.816  -17.761    1.592   20.124  139.444 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 182.26850  113.79175   1.602 0.109553    
IMD          -0.29381    0.10610  -2.769 0.005736 ** 
age0.11       2.21553    1.36681   1.621 0.105376    
age12.17     -2.36944    1.94032  -1.221 0.222341    
age18.24     -0.16683    1.16041  -0.144 0.885719    
age25.34      2.31424    1.19221   1.941 0.052550 .  
age35.39      6.65665    2.65716   2.505 0.012413 *  
age50.59      6.31033    1.74161   3.623 0.000307 ***
age60.69      0.34605    1.46550   0.236 0.813386    
age70plus    -0.71097    1.23595  -0.575 0.565269    
density     164.39302  636.21170   0.258 0.796162    
carebeds      0.03583    0.01489   2.407 0.016292 *  
AandE         1.13369    4.03313   0.281 0.778703    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 31.75 on 911 degrees of freedom
Multiple R-squared:  0.2039,    Adjusted R-squared:  0.1934 
F-statistic: 19.44 on 12 and 911 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><br> which, as its R-squared value of 0.204 suggests, goes some way to explaining the variation in the rates. Note that you can tidier output for some models using tidyvere’s <a href="https://broom.tidymodels.org/" target="_blank">broom</a> package and functions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(broom)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(ols1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 5
   term        estimate std.error statistic  p.value
   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 (Intercept) 182.      114.         1.60  0.110   
 2 IMD          -0.294     0.106     -2.77  0.00574 
 3 age0.11       2.22      1.37       1.62  0.105   
 4 age12.17     -2.37      1.94      -1.22  0.222   
 5 age18.24     -0.167     1.16      -0.144 0.886   
 6 age25.34      2.31      1.19       1.94  0.0525  
 7 age35.39      6.66      2.66       2.51  0.0124  
 8 age50.59      6.31      1.74       3.62  0.000307
 9 age60.69      0.346     1.47       0.236 0.813   
10 age70plus    -0.711     1.24      -0.575 0.565   
11 density     164.      636.         0.258 0.796   
12 carebeds      0.0358    0.0149     2.41  0.0163  
13 AandE         1.13      4.03       0.281 0.779   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(ols1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.204         0.193  31.7      19.4 4.88e-38    12 -4500. 9027. 9095.
# … with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p>Looking at R’s standard diagnostic plots there is not any strong evidence that the standard ]residual Normality assumption](https://thestatsgeek.com/2013/08/07/assumptions-for-linear-regression/){target=“_blank”} of the regression statistics is being violated although, not very surprisingly, the variance inflation values (VIF) do suggest <a href="https://www.britannica.com/topic/collinearity-statistics" target="_blank">high levels of colinearity</a> between the age variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ols1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span>(<span class="st">"car"</span> <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[,<span class="dv">1</span>])) <span class="fu">install.packages</span>(<span class="st">"car"</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(car)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(ols1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      IMD   age0.11  age12.17  age18.24  age25.34  age35.39  age50.59  age60.69 
 2.834069 18.836543  6.050232 38.347245 27.513979 10.228388 16.430177 14.397087 
age70plus   density  carebeds     AandE 
38.881759  2.123517  1.135127  1.030432 </code></pre>
</div>
</div>
<p><img src="hazard.gif" class="img-fluid" width="75"></p>
<p><font size="3">There are no hard and fast rules but, in broad terms, a VIF value of 4 or 5 or above is worth considering as a potential issue and a value above 10 suggests a very high level of multicollinearity. The simple solution to the issue is to drop some of the colinear variables but not all: if X1 and X2 are highly correlated, you only need to consider dropping X1 or X2, not both.</font></p>
<p><br> Although I am generally cautious about automated selection procedures, in this case a stepwise model selection appears useful to address the colinearity:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>ols2 <span class="ot">&lt;-</span> <span class="fu">step</span>(ols1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The results are,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(ols2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept) 147.       14.4        10.3  1.96e-23
2 IMD          -0.260     0.0941     -2.76 5.90e- 3
3 age0.11       1.81      0.532       3.40 6.95e- 4
4 age25.34      2.91      0.476       6.11 1.48e- 9
5 age35.39      7.28      1.54        4.74 2.48e- 6
6 age50.59      6.66      0.638      10.4  3.60e-24
7 carebeds      0.0333    0.0142      2.35 1.91e- 2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(ols2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.201         0.196  31.7      38.5 8.36e-42     6 -4501. 9018. 9057.
# … with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(ols2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     IMD  age0.11 age25.34 age35.39 age50.59 carebeds 
2.236588 2.865175 4.394042 3.425196 2.212515 1.031632 </code></pre>
</div>
</div>
<p>An analysis of variance (ANOVA) shows there is no statistically gain in using the model with more variables (<code>ols1</code>) so we can prefer the simpler (<code>ols2</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ols2, ols1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Rate ~ IMD + age0.11 + age25.34 + age35.39 + age50.59 + carebeds
Model 2: Rate ~ IMD + age0.11 + age12.17 + age18.24 + age25.34 + age35.39 + 
    age50.59 + age60.69 + age70plus + density + carebeds + AandE
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1    917 921337                           
2    911 918176  6    3161.6 0.5228 0.7913</code></pre>
</div>
</div>
<p>Looking again at the model (<code>tidy(ols2)</code>), it may seem surprising that the deprivation index is negatively correlated with the COVID rate – implying more deprivation, fewer infections (geographies of health often work in the opposite direction; being poorer can come with a ‘health premium’) – but this is due to the later variants of the disease that spread quickly through more affluent populations when restrictions on mobility and social interaction have been relaxed.</p>
</section>
<section id="spatial-dependencies-in-the-model-residuals" class="level2">
<h2 class="anchored" data-anchor-id="spatial-dependencies-in-the-model-residuals">Spatial dependencies in the model residuals</h2>
<p>Although the model appears to fit the data reasonably well, there is a problem. The residuals – the differences between what the model predicts as the COVID-19 rate at each location and what those rates actually are – are supposed to be random noise, meaning their values should be independent of their location and of each other, with no spatial structure. They are not. In fact, if we apply a Moran’s test to the residuals, using the test for regression residuals, <code>lm.morantest()</code>, we find that they are significantly spatially correlated:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm.morantest</span>(ols2, spweight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Global Moran I for regression residuals

data:  
model: lm(formula = Rate ~ IMD + age0.11 + age25.34 + age35.39 +
age50.59 + carebeds, data = covid)
weights: spweight

Moran I statistic standard deviate = 22.357, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Observed Moran I      Expectation         Variance 
    0.4461249282    -0.0033794098     0.0004042296 </code></pre>
</div>
</div>
<p><br> The pattern is evident if we map the <a href="https://www.statology.org/standardized-residuals" target="_blank">standardised residuals</a> from the function <code>rstandard()</code>. At the risk of geographic over-simplification, there is something of a north-south divide, with a patch of negative residuals to the north of the study region. These are rural neighbouhoods where the model is under-predicting the rate of COVID-19 cases.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>covid<span class="sc">$</span>resids <span class="ot">&lt;-</span> <span class="fu">rstandard</span>(ols2)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>brks <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">min</span>(covid<span class="sc">$</span>resids), <span class="sc">-</span><span class="fl">3.29</span>, <span class="sc">-</span><span class="fl">2.58</span>, <span class="sc">-</span><span class="fl">1.96</span>, <span class="fl">1.96</span>, <span class="fl">2.58</span>, <span class="fl">3.29</span>,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>          <span class="fu">max</span>(covid<span class="sc">$</span>resids))</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>covid<span class="sc">$</span>resids_gp <span class="ot">&lt;-</span> <span class="fu">cut</span>(covid<span class="sc">$</span>resids, brks, <span class="at">include.lowest =</span> <span class="cn">TRUE</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>pal <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"purple"</span>, <span class="st">"dark blue"</span>, <span class="st">"light blue"</span>, <span class="st">"light grey"</span>, <span class="st">"yellow"</span>, <span class="st">"orange"</span>, <span class="st">"red"</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(covid, <span class="fu">aes</span>(<span class="at">fill =</span> resids_gp)) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">size =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="st">"Standardised residual"</span>, <span class="at">values =</span> pal) <span class="sc">+</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_legend</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="looking-again-at-the-model" class="level3">
<h3 class="anchored" data-anchor-id="looking-again-at-the-model">Looking again at the model</h3>
<p>It is possible that the spatial structure in the residuals exists because the model has been mis-specified. In particular, we might wonder if it was a mistake to drop the population density variable which perhaps had a polynomial (non-linear) relationship with the COVID rates. Let’s find out.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>ols3 <span class="ot">&lt;-</span> <span class="fu">update</span>(ols2, . <span class="sc">~</span> . <span class="sc">+</span> <span class="fu">poly</span>(density, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br> Certainly, of the three models, this is the best fit to the data, as we can see from the various model fit diagnostics that are easily gathered together using the <code>glance()</code> function. Note the <em>highest</em>, adjusted r-squared value and <em>lowest</em> AIC value, for example.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(<span class="fu">glance</span>(ols1), <span class="fu">glance</span>(ols2), <span class="fu">glance</span>(ols3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 12
  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.204         0.193  31.7      19.4 4.88e-38    12 -4500. 9027. 9095.
2     0.201         0.196  31.7      38.5 8.36e-42     6 -4501. 9018. 9057.
3     0.248         0.241  30.8      37.7 5.93e-52     8 -4473. 8966. 9015.
# … with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p>An analysis of variance also suggests that the model fit has improved significantly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ols2, ols3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Rate ~ IMD + age0.11 + age25.34 + age35.39 + age50.59 + carebeds
Model 2: Rate ~ IMD + age0.11 + age25.34 + age35.39 + age50.59 + carebeds + 
    poly(density, 2)
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1    917 921337                                  
2    915 867305  2     54032 28.502 9.819e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>However, there is still spatial autocorrelation left in the model residuals, albeit slightly reduced from before.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm.morantest</span>(ols2, spweight)<span class="sc">$</span>estimate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Observed Moran I      Expectation         Variance 
    0.4461249282    -0.0033794098     0.0004042296 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm.morantest</span>(ols3, spweight)<span class="sc">$</span>estimate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Observed Moran I      Expectation         Variance 
    0.4133475904    -0.0037610429     0.0004036032 </code></pre>
</div>
</div>
<p>The map of the residuals now looks like:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>covid<span class="sc">$</span>resids <span class="ot">&lt;-</span> <span class="fu">rstandard</span>(ols3)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>brks <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">min</span>(covid<span class="sc">$</span>resids), <span class="sc">-</span><span class="fl">3.29</span>, <span class="sc">-</span><span class="fl">2.58</span>, <span class="sc">-</span><span class="fl">1.96</span>, <span class="fl">1.96</span>, <span class="fl">2.58</span>, <span class="fl">3.29</span>,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>          <span class="fu">max</span>(covid<span class="sc">$</span>resids))</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>covid<span class="sc">$</span>resids_gp <span class="ot">&lt;-</span> <span class="fu">cut</span>(covid<span class="sc">$</span>resids, brks, <span class="at">include.lowest =</span> <span class="cn">TRUE</span>)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>pal <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"purple"</span>, <span class="st">"dark blue"</span>, <span class="st">"light blue"</span>, <span class="st">"light grey"</span>, <span class="st">"yellow"</span>, <span class="st">"orange"</span>, <span class="st">"red"</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(covid, <span class="fu">aes</span>(<span class="at">fill =</span> resids_gp)) <span class="sc">+</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">size =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="st">"Standardised residual"</span>, <span class="at">values =</span> pal) <span class="sc">+</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_legend</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="spatial-regression-models" class="level2">
<h2 class="anchored" data-anchor-id="spatial-regression-models">Spatial regression models</h2>
<section id="spatial-error-model" class="level3">
<h3 class="anchored" data-anchor-id="spatial-error-model">Spatial error model</h3>
<p>One way to handle the error structure is to fit a spatial simultaneous autoregressive error model which decomposes the error (the residuals) into two parts: a spatially lagged component (the bit that allows for geographical clustering in the residuals) and a remaining error: <span class="math inline">\(y = X\beta + \lambda W \xi + \epsilon\)</span>. The model can be fitted using R’s <code>spatialreg</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span>(<span class="st">"spatialreg"</span> <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[,<span class="dv">1</span>])) <span class="fu">install.packages</span>(<span class="st">"spatialreg"</span>, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(spatialreg)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>errmod <span class="ot">&lt;-</span> <span class="fu">errorsarlm</span>(<span class="fu">formula</span>(ols3), <span class="at">data =</span> covid, <span class="at">listw =</span> spweight)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(errmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:errorsarlm(formula = formula(ols3), data = covid, listw = spweight)

Residuals:
     Min       1Q   Median       3Q      Max 
-88.9057 -13.5631   1.0775  15.1597 108.7168 

Type: error 
Coefficients: (asymptotic standard errors) 
                     Estimate  Std. Error z value  Pr(&gt;|z|)
(Intercept)        228.423031   13.194612 17.3118 &lt; 2.2e-16
IMD                 -0.595479    0.089535 -6.6508 2.915e-11
age0.11              1.885127    0.449453  4.1943 2.738e-05
age25.34             2.612570    0.416075  6.2791 3.406e-10
age35.39             3.729976    1.369957  2.7227  0.006475
age50.59             3.339294    0.608468  5.4880 4.064e-08
carebeds             0.051339    0.010181  5.0426 4.592e-07
poly(density, 2)1 -111.989485   38.123934 -2.9375  0.003309
poly(density, 2)2 -120.005334   28.931983 -4.1478 3.356e-05

Lambda: 0.69751, LR test value: 348.94, p-value: &lt; 2.22e-16
Asymptotic standard error: 0.028893
    z-value: 24.142, p-value: &lt; 2.22e-16
Wald statistic: 582.82, p-value: &lt; 2.22e-16

Log likelihood: -4298.755 for error model
ML residual variance (sigma squared): 572.93, (sigma: 23.936)
Number of observations: 924 
Number of parameters estimated: 11 
AIC: 8619.5, (AIC for lm: 8966.5)</code></pre>
</div>
</div>
<p>The spatial component, <span class="math inline">\(\lambda\)</span>, the spatial autocorrelation in the residuals, is significant as a number of test statistics that are with it in the summary above show. What it confirms is what we could interpret from the earlier Moran’s test of the regression residuals: having allowed for the variables that help to predict the COVID-rates there is still an unexplained geographic pattern whereby places for which the model over-predict the rate tend to be surrounded by other places where it does the same, and places where it under-predicts are surrounded by other under-predictions. The spatial error model gives a better fit to the data than the standard regression, as the following diagnostics tell us (the lower the AIC the better)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(ols3)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2479886</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(errmod)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5543411</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(ols3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8966.455</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(errmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8619.511</code></pre>
</div>
</div>
<p>The differences are such that there is little doubt that the error model offers a much improved fit but if we do wish to test that difference statistically then</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logLik</span>(ols3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' -4473.228 (df=10)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">logLik</span>(errmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' -4298.755 (df=11)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>degf <span class="ot">&lt;-</span> <span class="fu">attr</span>(<span class="fu">logLik</span>(errmod), <span class="st">"df"</span>) <span class="sc">-</span> <span class="fu">attr</span>(<span class="fu">logLik</span>(ols3), <span class="st">"df"</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>LR <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> (<span class="fu">logLik</span>(ols3) <span class="sc">-</span> <span class="fu">logLik</span>(errmod))</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>LR <span class="sc">&gt;</span> <span class="fu">qchisq</span>(<span class="fl">0.99</span>, degf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>Using the error model changes the estimates of the regression coefficients.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(ols3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 5
  term               estimate std.error statistic  p.value
  &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)        185.       15.2       12.2   7.36e-32
2 IMD                 -0.338     0.0941    -3.59  3.45e- 4
3 age0.11              1.51      0.519      2.92  3.61e- 3
4 age25.34             3.15      0.464      6.80  1.87e-11
5 age35.39             3.96      1.56       2.55  1.11e- 2
6 age50.59             5.67      0.696      8.15  1.15e-15
7 carebeds             0.0290    0.0138     2.10  3.56e- 2
8 poly(density, 2)1   23.8      43.1        0.553 5.81e- 1
9 poly(density, 2)2 -267.       35.5       -7.54  1.11e-13</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(errmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 5
   term               estimate std.error statistic  p.value
   &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 (Intercept)        228.       13.2        17.3  0       
 2 IMD                 -0.595     0.0895     -6.65 2.91e-11
 3 age0.11              1.89      0.449       4.19 2.74e- 5
 4 age25.34             2.61      0.416       6.28 3.41e-10
 5 age35.39             3.73      1.37        2.72 6.48e- 3
 6 age50.59             3.34      0.608       5.49 4.06e- 8
 7 carebeds             0.0513    0.0102      5.04 4.59e- 7
 8 poly(density, 2)1 -112.       38.1        -2.94 3.31e- 3
 9 poly(density, 2)2 -120.       28.9        -4.15 3.36e- 5
10 lambda               0.698     0.0289     24.1  0       </code></pre>
</div>
</div>
<p>For example, where the estimate for <code>age50.59</code>, which is the estimate of the effect size, used to be 5.67, now it is 3.34. The 95% confidence intervals for those and the other coefficient estimates change too:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(ols3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          2.5 %        97.5 %
(Intercept)        1.555316e+02  215.12202256
IMD               -5.225593e-01   -0.15331307
age0.11            4.956890e-01    2.53253071
age25.34           2.244363e+00    4.06480619
age35.39           9.064758e-01    7.01079426
age50.59           4.308470e+00    7.03988250
carebeds           1.958051e-03    0.05604307
poly(density, 2)1 -6.079177e+01  108.44040596
poly(density, 2)2 -3.369641e+02 -197.81320842</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(errmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          2.5 %       97.5 %
lambda               0.64088619   0.75414281
(Intercept)        202.56206649 254.28399509
IMD                 -0.77096349  -0.41999361
age0.11              1.00421453   2.76603896
age25.34             1.79707796   3.42806128
age35.39             1.04490945   6.41504355
age50.59             2.14672005   4.53186895
carebeds             0.03138441   0.07129323
poly(density, 2)1 -186.71102210 -37.26794826
poly(density, 2)2 -176.71097755 -63.29968970</code></pre>
</div>
</div>
</section>
<section id="spatially-lagged-y-model" class="level3">
<h3 class="anchored" data-anchor-id="spatially-lagged-y-model">Spatially lagged y model</h3>
<p>Although the spatial error model fits the data better than the standard regression model, it tells us only that there is an unexplained spatial structure to the residuals, not what caused it. It may offer better estimates of the model parameters and their statistical significance but it does not presuppose any particular spatial process generating the patterns in the values. A different model that explicitly tests for whether the value at a location is functionally dependent on the values of neighbouring location is the spatially lagged y model: <span class="math inline">\(y = \rho Wy + X\beta + \epsilon\)</span>. It models an ‘overspill’ or chain effect where the outcome (the Y value) at any location is affected by the outcomes at surrounding locations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>lagmod <span class="ot">&lt;-</span> <span class="fu">lagsarlm</span>(<span class="fu">formula</span>(ols3), <span class="at">data =</span> covid, <span class="at">listw =</span> spweight)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lagmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:lagsarlm(formula = formula(ols3), data = covid, listw = spweight)

Residuals:
     Min       1Q   Median       3Q      Max 
-98.8140 -14.8770   1.0467  14.7420 110.1081 

Type: lag 
Coefficients: (asymptotic standard errors) 
                     Estimate  Std. Error z value  Pr(&gt;|z|)
(Intercept)         17.353050   14.403449  1.2048 0.2282866
IMD                 -0.371501    0.074903 -4.9598 7.057e-07
age0.11              1.377790    0.411239  3.3503 0.0008071
age25.34             2.678105    0.367344  7.2905 3.089e-13
age35.39             1.885234    1.235376  1.5260 0.1269996
age50.59             3.636195    0.553621  6.5680 5.099e-11
carebeds             0.042747    0.010887  3.9264 8.623e-05
poly(density, 2)1  -69.714325   34.062239 -2.0467 0.0406900
poly(density, 2)2 -156.910145   28.073145 -5.5893 2.279e-08

Rho: 0.63167, LR test value: 342.73, p-value: &lt; 2.22e-16
Asymptotic standard error: 0.02966
    z-value: 21.297, p-value: &lt; 2.22e-16
Wald statistic: 453.57, p-value: &lt; 2.22e-16

Log likelihood: -4301.863 for lag model
ML residual variance (sigma squared): 591.59, (sigma: 24.323)
Number of observations: 924 
Number of parameters estimated: 11 
AIC: 8625.7, (AIC for lm: 8966.5)
LM test for residual autocorrelation
test value: 3.5747, p-value: 0.058666</code></pre>
</div>
</div>
<p>Its test for residual autocorrelation does not generate a statistically significant result at a 95% level, meaning there is no statistically significant spatial structure now left in the residuals, although it is close.</p>
<p>Note that the beta estimates of the lagged y-model cannot be interpreted in the same way as for a standard regression model. For example, the beta estimate of -0.372 for the <code>IMD</code> variable does not mean that if (hypothetically) we increased that variable by one unit at each location we should then expect the COVID-19 to everywhere decrease by 0.372 holding the other X variables constant. That is the correct interpretation for a standard (OLS) regression model and also for the spatial error model but not for where the lag of the Y variable is included as a predictor variable. The reason is because if we did raise the <code>IMD</code> value it would start something akin to a ‘chain reaction’ through the feedback of Y via the lagged Y values: the (hypothetical) increase in deprivation at the one location, decreases the COVID-19 rate at neighbouring locations, which decrease the rate at their neighbours and so forth. The total impact is a sum of the direct effect – that predicted to happen through the 1 unit change in <code>IMD</code> – and the indirect effect, which is that caused by ‘the chain reaction’ / feedback / ‘overspill’ in the system:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">impacts</span>(lagmod, <span class="at">listw =</span> spweight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Impact measures (lag, exact):
                        Direct     Indirect       Total
IMD                 -0.4123766   -0.5962428   -1.008619
age0.11              1.5293852    2.2112917    3.740677
age25.34             2.9727718    4.2982407    7.271013
age35.39             2.0926626    3.0257175    5.118380
age50.59             4.0362780    5.8359322    9.872210
carebeds             0.0474502    0.0686068    0.116057
poly(density, 2)1  -77.3848558 -111.8884195 -189.273275
poly(density, 2)2 -174.1746600 -251.8338663 -426.008526</code></pre>
</div>
</div>
<p>Although it wasn’t especially noticeable, there was a short pause as those impacts were calculated. The calculations could take much longer if the size of the spatial weights matrix was larger. As <a href="https://maczokni.github.io/crime_mapping_textbook/spatial-regression-models.html#fitting-and-interpreting-a-spatially-lagged-model" target="_blank">this author</a> notes, after <a href="https://www.routledge.com/Introduction-to-Spatial-Econometrics/LeSage-Pace/p/book/9781420064247" target="_blank">Lesage and Pace, 2009</a>, a faster approximation method can be used, here with <code>R = 1000</code> simulated distributions for the impact measures.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> <span class="fu">as</span>(spweight, <span class="st">"CsparseMatrix"</span>)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>trMC <span class="ot">&lt;-</span> <span class="fu">trW</span>(W, <span class="at">type =</span> <span class="st">"MC"</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>im <span class="ot">&lt;-</span><span class="fu">summary</span>(<span class="fu">impacts</span>(lagmod, <span class="at">tr =</span> trMC, <span class="at">R =</span> <span class="dv">1000</span>), <span class="at">zstats =</span> <span class="cn">TRUE</span>)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(im<span class="sc">$</span>res, <span class="at">row.names =</span> <span class="fu">names</span>(lagmod<span class="sc">$</span>coefficients)[<span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         direct      indirect        total
IMD                 -0.41217413   -0.59644414   -1.0086183
age0.11              1.52863446    2.21203856    3.7406730
age25.34             2.97131258    4.29969241    7.2710050
age35.39             2.09163539    3.02673938    5.1183748
age50.59             4.03429679    5.83790323    9.8722000
carebeds             0.04742691    0.06862998    0.1160569
poly(density, 2)1  -77.34687053 -111.92620885 -189.2730794
poly(density, 2)2 -174.08916443 -251.91892111 -426.0080855</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>                                          <span class="co"># The [-1] is to omit the intercept</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>An advantage of this approach is that we can also obtain z and p-values for the impact measures; i.e.&nbsp;measures of statistical significance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(im<span class="sc">$</span>zmat, <span class="at">row.names =</span> <span class="fu">names</span>(lagmod<span class="sc">$</span>coefficients)[<span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Direct  Indirect     Total
IMD               -5.009567 -4.384977 -4.783372
age0.11            3.407586  3.189026  3.335795
age25.34           7.188060  5.416559  6.350412
age35.39           1.581328  1.559155  1.576863
age50.59           6.469422  5.231091  5.967869
carebeds           3.896181  3.488718  3.724252
poly(density, 2)1 -2.068516 -1.982364 -2.032422
poly(density, 2)2 -5.514659 -4.560168 -5.092320</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(im<span class="sc">$</span>pzmat, <span class="at">row.names =</span> <span class="fu">names</span>(lagmod<span class="sc">$</span>coefficients)[<span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Direct     Indirect        Total
IMD               5.455269e-07 1.159982e-05 1.723790e-06
age0.11           6.554031e-04 1.427532e-03 8.505571e-04
age25.34          6.572520e-13 6.075694e-08 2.147396e-10
age35.39          1.138030e-01 1.189597e-01 1.148270e-01
age50.59          9.837842e-11 1.685127e-07 2.403716e-09
carebeds          9.772117e-05 4.853426e-04 1.958949e-04
poly(density, 2)1 3.859154e-02 4.743853e-02 4.211099e-02
poly(density, 2)2 3.494575e-08 5.111269e-06 3.537078e-07</code></pre>
</div>
</div>
<p>Most but not all of the impacts are significant at, say, a 95% confidence (i.e p &lt; 0.05). We can drop <code>age35.39</code> from the model with little loss of fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>lagmod2 <span class="ot">&lt;-</span> <span class="fu">lagsarlm</span>(Rate <span class="sc">~</span>  IMD <span class="sc">+</span> age0<span class="fl">.11</span> <span class="sc">+</span> age25<span class="fl">.34</span> <span class="sc">+</span> age50<span class="fl">.59</span> <span class="sc">+</span> carebeds <span class="sc">+</span> </span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">poly</span>(density, <span class="dv">2</span>), <span class="at">data =</span> covid, <span class="at">listw =</span> spweight)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(lagmod, lagmod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Model df    AIC  logLik Test L.Ratio p-value
lagmod      1 11 8625.7 -4301.9    1                
lagmod2     2 10 8626.1 -4303.0    2  2.3408 0.12602</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(<span class="fu">glance</span>(lagmod), <span class="fu">glance</span>(lagmod2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  r.squared   AIC   BIC deviance logLik  nobs
      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt;
1     0.532 8626. 8679.  546629. -4302.   924
2     0.532 8626. 8674.  547460. -4303.   924</code></pre>
</div>
</div>
<p><br> In fact, an increase of 1 unit in, for example, the <code>IMD</code> variable, will play out slightly differently in different places because they have different neighbours with different Y values and are at different distances from each other. The code below, which is from the first edition of <a href="https://uk.sagepub.com/en-gb/eur/spatial-regression-models/book262155" target="_blank">Ward &amp; Gleditsch (2008, pp.47)</a>, will calculate the impact (of a one unit change in <code>IMD</code>) at each location but below I have limited it to the first ten so that it doesn’t take too long to run.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(covid)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>I <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="at">nrow =</span> n, <span class="at">ncol =</span> n)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(I) <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>rho <span class="ot">&lt;-</span> lagmod<span class="sc">$</span>rho</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> lagmod<span class="sc">$</span>coefficients[<span class="st">"age25.34"</span>]</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>weights.matrix <span class="ot">&lt;-</span> <span class="fu">listw2mat</span>(spweight)</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="at">times=</span><span class="dv">10</span>)</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, \(i) {</span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>  xvector <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="at">times=</span>n)</span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>  xvector[i] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a>  impact <span class="ot">&lt;-</span> <span class="fu">solve</span>(I <span class="sc">-</span> rho <span class="sc">*</span> weights.matrix) <span class="sc">%*%</span> xvector <span class="sc">*</span> beta</span>
<span id="cb81-12"><a href="#cb81-12" aria-hidden="true" tabindex="-1"></a>  results[i] <span class="ot">&lt;-</span> impact[i]</span>
<span id="cb81-13"><a href="#cb81-13" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb81-14"><a href="#cb81-14" aria-hidden="true" tabindex="-1"></a>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 2.953840 2.973231 2.949515 2.908907 3.025483 2.901597 2.949316 2.960332
 [9] 2.949171 2.946591</code></pre>
</div>
</div>
</section>
<section id="choosing-between-the-spatial-error-and-lagged-y-model" class="level3">
<h3 class="anchored" data-anchor-id="choosing-between-the-spatial-error-and-lagged-y-model">Choosing between the spatial error and lagged y model</h3>
<p>Before fitting the spatial error and lagged y models, we could have looked for evidence in support of them using the function <code>lm.LMtests()</code>. This tests the basic OLS specification against the more general spatial error and lagged y models. Anselin and Rey (2014, p.110) offer the following decision tree that can, in the absence of a more theoretical basis for the model choice (e.g.&nbsp;the type of process being modelled), be used in conjunction with the test results to help select the model.</p>
<p><img src="flowchart.jpg" class="img-fluid"></p>
<p><font size="2">Source: <a href="https://www.amazon.co.uk/Modern-Spatial-Econometrics-Practice-GeoDaSpace/dp/0986342106" target="&quot;_blank">Modern Spatial Econometrics in Practice</a></font></p>
<p>In the first step, we find that in this instance both the LM-Error and LM-Lag tests are significant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>ols4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Rate <span class="sc">~</span>  IMD <span class="sc">+</span> age0<span class="fl">.11</span> <span class="sc">+</span> age25<span class="fl">.34</span> <span class="sc">+</span> age50<span class="fl">.59</span> <span class="sc">+</span> carebeds <span class="sc">+</span> <span class="fu">poly</span>(density, <span class="dv">2</span>), <span class="at">data =</span> covid)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm.LMtests</span>(ols4, spweight, <span class="at">test=</span><span class="fu">c</span>(<span class="st">"LMerr"</span>, <span class="st">"LMlag"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Lagrange multiplier diagnostics for spatial dependence

data:  
model: lm(formula = Rate ~ IMD + age0.11 + age25.34 + age50.59 +
carebeds + poly(density, 2), data = covid)
weights: spweight

LMerr = 411.48, df = 1, p-value &lt; 2.2e-16


    Lagrange multiplier diagnostics for spatial dependence

data:  
model: lm(formula = Rate ~ IMD + age0.11 + age25.34 + age50.59 +
carebeds + poly(density, 2), data = covid)
weights: spweight

LMlag = 463.85, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Moving on to the robust tests, only the LM-Lag test is significant. Given the nature of COVID-19 as an infectious disease, it does seem reasonable to suppose that high rates of infection in any an area will ‘overspill’ into neighbouring areas too.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm.LMtests</span>(ols4, spweight, <span class="at">test=</span><span class="fu">c</span>(<span class="st">"RLMerr"</span>, <span class="st">"RLMlag"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Lagrange multiplier diagnostics for spatial dependence

data:  
model: lm(formula = Rate ~ IMD + age0.11 + age25.34 + age50.59 +
carebeds + poly(density, 2), data = covid)
weights: spweight

RLMerr = 2.3319, df = 1, p-value = 0.1267


    Lagrange multiplier diagnostics for spatial dependence

data:  
model: lm(formula = Rate ~ IMD + age0.11 + age25.34 + age50.59 +
carebeds + poly(density, 2), data = covid)
weights: spweight

RLMlag = 54.693, df = 1, p-value = 1.409e-13</code></pre>
</div>
</div>
</section>
</section>
<section id="a-geographically-weighted-spatial-weights-matrix" class="level2">
<h2 class="anchored" data-anchor-id="a-geographically-weighted-spatial-weights-matrix">A geographically weighted spatial weights matrix</h2>
<p>As with the tests of spatial autocorrelation in an earlier session and as with the geographically weighted statistics, the results of the spatial regression models are dependent on the specification of the spatial weights matrix which can suffer from being somewhat arbitrary. We could, if we wish, try calibrating it around the geographically weighted mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(GWmodel)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(Rate <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> covid_sp, <span class="at">adaptive =</span> <span class="cn">TRUE</span>, <span class="at">kernel =</span> <span class="st">"bisquare"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To now create the corresponding inverse distance spatial weights matrix for the models, we can use the <code>nn2</code> function in the <code>RANN</code> package to find the $bw = $ 18 nearest neighbours to each centroid point:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span>(<span class="st">"RANN"</span> <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[,<span class="dv">1</span>]))  <span class="fu">install.packages</span>(<span class="st">"RANN"</span>)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(RANN)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(<span class="fu">st_centroid</span>(<span class="fu">st_geometry</span>(covid)))</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>knn <span class="ot">&lt;-</span> <span class="fu">nn2</span>(coords, coords, <span class="at">k =</span> bw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Having done so, those neighbours can be geographically weighted using a bisquare kernel, as in the GWR calibration above. (A Gaussian kernel is obtained if <code>(1 - (x / max(x))^2)^2</code> is replaced by <code>exp(-0.5 * (x / max(x))^2)</code> in the code below).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> knn<span class="sc">$</span>nn.dists</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>glist <span class="ot">&lt;-</span> <span class="fu">apply</span>(d, <span class="dv">1</span>, \(x) {</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">1</span> <span class="sc">-</span> (x <span class="sc">/</span> <span class="fu">max</span>(x))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>}, <span class="at">simplify =</span> <span class="cn">FALSE</span>)</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>knearnb <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(<span class="fu">st_centroid</span>(<span class="fu">st_geometry</span>(covid)), <span class="at">k =</span> bw))</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>spweightK <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(knearnb, glist, <span class="at">style =</span> <span class="st">"C"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The results are not very successful though. The lag model with contiguous spatial weights fits the data better,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>lagmod3 <span class="ot">&lt;-</span> <span class="fu">lagsarlm</span>(<span class="fu">formula</span>(ols4), <span class="at">data =</span> covid, <span class="at">listw =</span> spweightK)</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(<span class="fu">glance</span>(lagmod2), <span class="fu">glance</span>(lagmod3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  r.squared   AIC   BIC deviance logLik  nobs
      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt;
1     0.532 8626. 8674.  547460. -4303.   924
2     0.254 8959. 9008.  860562. -4470.   924</code></pre>
</div>
</div>
<p>In addition, the inverse distance weights are not row-standardised, which may cause some knock-on problems. They could become row-standardised (<code>spweightK &lt;- nb2listw(knearnb, glist, style = "W")</code>) but if they are, by re-scaling each row of the weights to equal one, then the inverse distance weighting is altered.</p>
</section>
<section id="geographically-weighted-regression" class="level2">
<h2 class="anchored" data-anchor-id="geographically-weighted-regression">Geographically Weighted Regression</h2>
<p>The following charts shows the simple, bivariate regression relationship between <code>Rate</code> and <code>age0.11</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(covid, <span class="fu">aes</span>(<span class="at">x =</span> age0<span class="fl">.11</span>, <span class="at">y =</span> Rate)) <span class="sc">+</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Intriguingly, it doesn’t seem to be linear relationship but a polynomial one.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(covid, <span class="fu">aes</span>(<span class="at">x =</span> age0<span class="fl">.11</span>, <span class="at">y =</span> Rate)) <span class="sc">+</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It could be that the relationship is indeed curved but it might also be that the nature of the relationship is spatially dependent – that the relationship between <code>Rate</code> and <code>age0.11</code> depends upon where it is measured. A <code>coplot()</code> from R’s base graphics lends weight to the second idea: note how the regression relationship changes with <code>X</code> and <code>Y</code>, which are the centroids of the neighbourhoods in the North West of England.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>coplot_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">st_coordinates</span>(<span class="fu">st_centroid</span>(covid)), <span class="at">Rate =</span> covid<span class="sc">$</span>Rate, <span class="at">age0.11 =</span> covid<span class="sc">$</span>age0<span class="fl">.11</span>)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>PointsWithLine <span class="ot">=</span> <span class="cf">function</span>(x, y, ...) {</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">points</span>(<span class="at">x=</span>x, <span class="at">y=</span>y, <span class="at">pch=</span><span class="dv">20</span>, <span class="at">col=</span><span class="st">"black"</span>)</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abline</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x))</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coplot</span>(Rate <span class="sc">~</span> age0<span class="fl">.11</span> <span class="sc">|</span> X <span class="sc">*</span> Y, <span class="at">data =</span> coplot_df, <span class="at">panel =</span> PointsWithLine, <span class="at">overlap =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Imagine, now, that instead of dividing the geography of the North West’s neighbourhoods into a <span class="math inline">\(6 \times 6\)</span> grid, as in the coplot, we instead go from location to location within the study region, calculating a <a href="https://www.sciencedirect.com/science/article/pii/B9780080449104004478?via%3Dihub" target="_blank">geographically weighted regression</a> at and around each one of them. This builds on the idea of geographically weighted statistics that allow the measured value of the statistic to vary locally from location to location across the study region; with geographically weighted it is the locally estimated regression coefficients that are allowed to vary. These are used to look for spatial variation in the regression relationships.</p>
<p>If the bandwidth is not known or there is no theoretical justification for it, it can be found using an automated selection procedure, here with a more complex model than the bivariate relationship shown in the coplot, instead using all the variables included in the choice between the spatial error and lagged y model, above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(GWmodel)</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(<span class="fu">formula</span>(ols4), <span class="at">data =</span> covid_sp, <span class="at">adaptive =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The model can then be fitted.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>gwrmod <span class="ot">&lt;-</span> <span class="fu">gwr.basic</span>(<span class="fu">formula</span>(ols4), <span class="at">data =</span> covid_sp, <span class="at">adaptive =</span> <span class="cn">TRUE</span>, <span class="at">bw =</span> bw)</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>gwrmod</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ***********************************************************************
   *                       Package   GWmodel                             *
   ***********************************************************************
   Program starts at: 2023-03-03 17:36:17 
   Call:
   gwr.basic(formula = formula(ols4), data = covid_sp, bw = bw, 
    adaptive = TRUE)

   Dependent (y) variable:  Rate
   Independent variables:  IMD age0.11 age25.34 age50.59 carebeds density
   Number of data points: 924
   ***********************************************************************
   *                    Results of Global Regression                     *
   ***********************************************************************

   Call:
    lm(formula = formula, data = data)

   Residuals:
     Min       1Q   Median       3Q      Max 
-123.194  -18.380    1.473   20.623  127.554 

   Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
   (Intercept)        188.50375   15.17560  12.422  &lt; 2e-16 ***
   IMD                 -0.39649    0.09149  -4.334 1.63e-05 ***
   age0.11              2.30191    0.41777   5.510 4.66e-08 ***
   age25.34             3.93517    0.34898  11.276  &lt; 2e-16 ***
   age50.59             5.80810    0.69596   8.345 2.59e-16 ***
   carebeds             0.02904    0.01382   2.101   0.0359 *  
   poly(density, 2)1   29.14870   43.19300   0.675   0.4999    
   poly(density, 2)2 -292.74904   34.12420  -8.579  &lt; 2e-16 ***

   ---Significance stars
   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
   Residual standard error: 30.88 on 916 degrees of freedom
   Multiple R-squared: 0.2427
   Adjusted R-squared: 0.2369 
   F-statistic: 41.93 on 7 and 916 DF,  p-value: &lt; 2.2e-16 
   ***Extra Diagnostic information
   Residual sum of squares: 873446.4
   Sigma(hat): 30.77887
   AIC:  8970.975
   AICc:  8971.172
   BIC:  8151.892
   ***********************************************************************
   *          Results of Geographically Weighted Regression              *
   ***********************************************************************

   *********************Model calibration information*********************
   Kernel function: bisquare 
   Adaptive bandwidth: 80 (number of nearest neighbours)
   Regression points: the same locations as observations are used.
   Distance metric: Euclidean distance metric is used.

   ****************Summary of GWR coefficient estimates:******************
                            Min.     1st Qu.      Median     3rd Qu.     Max.
   Intercept         -3.9934e+01  1.3693e+02  2.1422e+02  2.6180e+02 419.5064
   IMD               -2.7499e+00 -7.8059e-01 -4.4223e-01 -1.6702e-01   0.6501
   age0.11           -4.0541e+00  2.3759e-01  3.4220e+00  6.1701e+00  12.5921
   age25.34          -3.9387e+00  1.6469e+00  2.6274e+00  4.2843e+00  13.8157
   age50.59          -9.5346e+00  2.1727e+00  5.3255e+00  8.6233e+00  14.3515
   carebeds          -5.6126e-02  2.5983e-02  5.8662e-02  8.7463e-02   0.2220
   poly(density, 2)1 -2.7204e+03 -4.1814e+02 -1.5602e+02  4.1180e-01 667.9061
   poly(density, 2)2 -2.1980e+03 -5.4619e+02 -2.5300e+02 -1.2247e+02 643.0451
   ************************Diagnostic information*************************
   Number of data points: 924 
   Effective number of parameters (2trace(S) - trace(S'S)): 270.2441 
   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 653.7559 
   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 8552.959 
   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 8216.682 
   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 8513.32 
   Residual sum of squares: 313860.8 
   R-square value:  0.7278617 
   Adjusted R-square value:  0.6151951 

   ***********************************************************************
   Program stops at: 2023-03-03 17:36:17 </code></pre>
</div>
</div>
<p>The output requires some interpretation! The results of the global regression are those obtained from a standard OLS regression (i.e.&nbsp;<code>summary(lm(formula(ols4), data = covid_sp))</code>). It is ‘global’ because it is a model for the entire study region, without spatial variation in the regression estimates. The results of the geographically weighted regression are the results from, in this case, 924 separate but spatially overlapping regression models fitted, with geographic weighting, to spatial subsets of the data. All the local estimates are contained in the spatial data frame, <code>gwrmod$SDF</code>, including those for <code>age0.11</code> which are in <code>gwrmod$SDF$age0.11</code> and have the following distribution,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gwrmod<span class="sc">$</span>SDF<span class="sc">$</span>age0<span class="fl">.11</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-4.0541  0.2376  3.4220  3.3645  6.1701 12.5921 </code></pre>
</div>
</div>
<p>This is the same summary of the distribution that is included in the GWR coefficient estimates. What it means is that in at least one location the relationship of <code>age0.11</code> to <code>Rate</code> is, conditional on the other variables, negative. It is more usual for it to be positive – more children, more infections (perhaps a school effect?) – but the estimated effect size varies quite substantially across the locations in the study region. Its interquartile range is from 0.238 to 6.17. Mapping these local estimates reveals an interesting geography – it is largely in and around Manchester where a greater number of children of primary school age or younger appears to <em>lower</em> instead of raising the infection rate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>covid<span class="sc">$</span>age0<span class="fl">.11</span>GWR <span class="ot">&lt;-</span> gwrmod<span class="sc">$</span>SDF<span class="sc">$</span>age0<span class="fl">.11</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> covid, <span class="fu">aes</span>(<span class="at">fill =</span> age0<span class="fl">.11</span>GWR)) <span class="sc">+</span></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">size =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(<span class="st">"beta"</span>, <span class="at">mid =</span> <span class="st">"grey90"</span>, <span class="at">trans =</span> <span class="st">"reverse"</span>) <span class="sc">+</span></span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_colourbar</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>With a bit of effort we can get all the variables on the same chart…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span>(<span class="st">"gridExtra"</span> <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[,<span class="dv">1</span>])) <span class="fu">install.packages</span>(<span class="st">"gridExtra"</span>,</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>                                                          <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(gridExtra)</span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">8</span>, \(j) {</span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(gwrmod<span class="sc">$</span>SDF[, j]) <span class="sc">%&gt;%</span></span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">beta =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> beta)) <span class="sc">+</span></span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_sf</span>(<span class="at">col =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb101-9"><a href="#cb101-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">scale_fill_gradient2</span>(<span class="st">"beta"</span>, <span class="at">mid =</span> <span class="st">"grey90"</span>, <span class="at">trans =</span> <span class="st">"reverse"</span>) <span class="sc">+</span></span>
<span id="cb101-10"><a href="#cb101-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb101-11"><a href="#cb101-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_colourbar</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>)) <span class="sc">+</span></span>
<span id="cb101-12"><a href="#cb101-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ggtitle</span>(<span class="fu">names</span>(gwrmod<span class="sc">$</span>SDF[j]))</span>
<span id="cb101-13"><a href="#cb101-13" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb101-14"><a href="#cb101-14" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(<span class="at">grobs =</span> g)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>… however, not all of these regression estimates are necessarily statistically significant. If we use the estimated t-values to isolate those that are not (t-values less than -1.96 or greater than +1.96 can be considered significant at a 95% confidence), then, for the <code>age0.11</code> variable we obtain,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>covid<span class="sc">$</span>age0<span class="fl">.11</span>GWR[<span class="fu">abs</span>(gwrmod<span class="sc">$</span>SDF<span class="sc">$</span>age0<span class="fl">.11</span>_TV) <span class="sc">&lt;</span> <span class="fl">1.96</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> covid, <span class="fu">aes</span>(<span class="at">fill =</span> age0<span class="fl">.11</span>GWR)) <span class="sc">+</span></span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">size =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(<span class="st">"beta"</span>, <span class="at">mid =</span> <span class="st">"grey90"</span>, <span class="at">na.value =</span> <span class="st">"white"</span>,</span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">trans =</span> <span class="st">"reverse"</span>) <span class="sc">+</span></span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_colourbar</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>and, with a bit more data wrangling, for the full set,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>sdf <span class="ot">&lt;-</span> <span class="fu">slot</span>(gwrmod<span class="sc">$</span>SDF, <span class="st">"data"</span>)</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">8</span>, \(j) {</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(gwrmod<span class="sc">$</span>SDF[, j]) </span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a>  t <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">names</span>(sdf) <span class="sc">==</span> <span class="fu">paste0</span>(<span class="fu">names</span>(x)[<span class="dv">1</span>],<span class="st">"_TV"</span>))</span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a>  x[<span class="fu">abs</span>(sdf[, t]) <span class="sc">&lt;</span> <span class="fl">1.96</span>, <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb103-6"><a href="#cb103-6" aria-hidden="true" tabindex="-1"></a>  x <span class="sc">%&gt;%</span></span>
<span id="cb103-7"><a href="#cb103-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">beta =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb103-8"><a href="#cb103-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> beta)) <span class="sc">+</span></span>
<span id="cb103-9"><a href="#cb103-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_sf</span>(<span class="at">col =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb103-10"><a href="#cb103-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">scale_fill_gradient2</span>(<span class="st">"beta"</span>, <span class="at">mid =</span> <span class="st">"grey90"</span>, <span class="at">na.value =</span> <span class="st">"white"</span>,</span>
<span id="cb103-11"><a href="#cb103-11" aria-hidden="true" tabindex="-1"></a>                           <span class="at">trans =</span> <span class="st">"reverse"</span>) <span class="sc">+</span></span>
<span id="cb103-12"><a href="#cb103-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb103-13"><a href="#cb103-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_colourbar</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>)) <span class="sc">+</span></span>
<span id="cb103-14"><a href="#cb103-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ggtitle</span>(<span class="fu">names</span>(gwrmod<span class="sc">$</span>SDF[j]))</span>
<span id="cb103-15"><a href="#cb103-15" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb103-16"><a href="#cb103-16" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(<span class="at">grobs =</span> g)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><img src="hazard.gif" class="img-fluid" width="75"></p>
<p><font size="3">I am sure there is a more elegant way of doing this. Don’t worry about the code especially - the point is that not every estimate, everywhere, is significant.</font></p>
<p><br> As with the basic GW statistics, we can undertake a randomisation test to suggest whether the spatial variation in the coefficient estimates is statistically significant. <strong>However</strong> this takes some time to run – with the default <code>nsims = 99</code> simulations it took about 12 minutes on my laptop. <strong>I have ‘commented it out’ in the code block below with the suggestion that you don’t run it now.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># I suggest you do not run this</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="co"># gwr.mc &lt;- gwr.montecarlo(formula(ols4), covid_sp, adaptive = TRUE, bw = bw)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Instead, let’s jump straight to the results, which I have saved in a pre-prepared workspace.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="fu">url</span>(<span class="st">"https://github.com/profrichharris/profrichharris.github.io/raw/main/MandM/workspaces/gwrmc.RData"</span>)</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(url)</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a><span class="fu">close</span>(url)</span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>gwr.mc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  p-value
(Intercept)          0.40
IMD                  0.38
age0.11              0.00
age25.34             0.15
age50.59             0.22
carebeds             0.97
poly(density, 2)1    0.00
poly(density, 2)2    0.00</code></pre>
</div>
</div>
<section id="mixed-gwr" class="level3">
<h3 class="anchored" data-anchor-id="mixed-gwr">Mixed GWR</h3>
<p>It appears that only the <code>age0.11</code> and <code>density</code> variables exhibit significant spatial variation (p-value &lt; 0.05). In principle it is possible to drop the other variables out from the local estimates and treat them as fixed, global estimates instead, in a Mixed GWR model (mixed global and local regression estimates). In practice, it is generating an error.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This appears to generate an error</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>gwrmixd <span class="ot">&lt;-</span> <span class="fu">gwr.mixed</span>(Rate <span class="sc">~</span> IMD <span class="sc">+</span> age0<span class="fl">.11</span> <span class="sc">+</span> age25<span class="fl">.34</span> <span class="sc">+</span> age50<span class="fl">.59</span> <span class="sc">+</span> carebeds <span class="sc">+</span></span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">poly</span>(density, <span class="dv">2</span>),</span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> covid_sp,</span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">fixed.vars =</span> <span class="fu">c</span>(<span class="st">"IMD"</span>, <span class="st">"age25.34"</span>, <span class="st">"age50.59"</span>, <span class="st">"carebeds"</span>),</span>
<span id="cb107-6"><a href="#cb107-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">bw =</span> bw, <span class="at">adaptive =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can work around this, though, using partial regressions, regressing <code>Rate</code>, <code>age0.11</code> and <code>poly(density, 2)</code> on the fixed variables and using their residuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>density<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">poly</span>(covid<span class="sc">$</span>density, <span class="dv">2</span>)[, <span class="dv">1</span>]</span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>density<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">poly</span>(covid<span class="sc">$</span>density, <span class="dv">2</span>)[, <span class="dv">2</span>]</span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>covid_sp<span class="sc">$</span>RateR <span class="ot">&lt;-</span> <span class="fu">residuals</span>(<span class="fu">lm</span>(Rate <span class="sc">~</span> IMD <span class="sc">+</span> age25<span class="fl">.34</span> <span class="sc">+</span> age50<span class="fl">.59</span> <span class="sc">+</span> carebeds,</span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>                               <span class="at">data =</span> covid_sp))</span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a>covid_sp<span class="sc">$</span>age0<span class="fl">.11</span>R <span class="ot">&lt;-</span> <span class="fu">residuals</span>(<span class="fu">lm</span>(age0<span class="fl">.11</span> <span class="sc">~</span> IMD <span class="sc">+</span> age25<span class="fl">.34</span> <span class="sc">+</span> age50<span class="fl">.59</span> <span class="sc">+</span></span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a>                                    carebeds, <span class="at">data =</span> covid_sp))</span>
<span id="cb108-7"><a href="#cb108-7" aria-hidden="true" tabindex="-1"></a>covid_sp<span class="sc">$</span>density<span class="fl">.1</span>R <span class="ot">&lt;-</span> <span class="fu">residuals</span>(<span class="fu">lm</span>(density<span class="fl">.1</span> <span class="sc">~</span> IMD <span class="sc">+</span> age25<span class="fl">.34</span> <span class="sc">+</span> age50<span class="fl">.59</span> <span class="sc">+</span></span>
<span id="cb108-8"><a href="#cb108-8" aria-hidden="true" tabindex="-1"></a>                                    carebeds, <span class="at">data =</span> covid_sp))</span>
<span id="cb108-9"><a href="#cb108-9" aria-hidden="true" tabindex="-1"></a>covid_sp<span class="sc">$</span>density<span class="fl">.2</span>R <span class="ot">&lt;-</span> <span class="fu">residuals</span>(<span class="fu">lm</span>(density<span class="fl">.2</span> <span class="sc">~</span> IMD <span class="sc">+</span> age25<span class="fl">.34</span> <span class="sc">+</span> age50<span class="fl">.59</span> <span class="sc">+</span></span>
<span id="cb108-10"><a href="#cb108-10" aria-hidden="true" tabindex="-1"></a>                                    carebeds, <span class="at">data =</span> covid_sp))</span>
<span id="cb108-11"><a href="#cb108-11" aria-hidden="true" tabindex="-1"></a>fml <span class="ot">&lt;-</span> <span class="fu">formula</span>(RateR <span class="sc">~</span> age0<span class="fl">.11</span>R <span class="sc">+</span> density<span class="fl">.1</span>R <span class="sc">+</span> density<span class="fl">.2</span>R)</span>
<span id="cb108-12"><a href="#cb108-12" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(fml, <span class="at">data =</span> covid_sp, <span class="at">adaptive =</span> <span class="cn">TRUE</span>)</span>
<span id="cb108-13"><a href="#cb108-13" aria-hidden="true" tabindex="-1"></a>gwrmixd <span class="ot">&lt;-</span> <span class="fu">gwr.basic</span>(fml, <span class="at">data =</span> covid_sp, <span class="at">bw =</span> bw, <span class="at">adaptive =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here are the statistically significant results for the <code>age0.11</code> variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>covid<span class="sc">$</span>age0<span class="fl">.11</span>GWR <span class="ot">&lt;-</span> gwrmixd<span class="sc">$</span>SDF<span class="sc">$</span>age0<span class="fl">.11</span>R</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>covid<span class="sc">$</span>age0<span class="fl">.11</span>GWR[<span class="fu">abs</span>(gwrmixd<span class="sc">$</span>SDF<span class="sc">$</span>age0<span class="fl">.11</span>R_TV) <span class="sc">&gt;</span> <span class="fl">1.96</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> covid, <span class="fu">aes</span>(<span class="at">fill =</span> age0<span class="fl">.11</span>GWR)) <span class="sc">+</span></span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">size =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(<span class="st">"beta"</span>, <span class="at">mid =</span> <span class="st">"grey90"</span>, <span class="at">na.value =</span> <span class="st">"white"</span>, <span class="at">trans =</span> <span class="st">"reverse"</span>) <span class="sc">+</span></span>
<span id="cb109-6"><a href="#cb109-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb109-7"><a href="#cb109-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_colourbar</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="multiscale-gwr" class="level3">
<h3 class="anchored" data-anchor-id="multiscale-gwr">Multiscale GWR</h3>
<p>It is also possible to fit a Multiscale GWR, which allows for the possibility of a different bandwith for each variable – see <code>?gwr.multiscale</code>. Since there is no particular reason to presume that the bandwidth should be the same for all the variables, arguably Multiscale GWR should be preferred over standard GWR, at least in the first instance. Its main drawback, however, is that it takes a while to run – over 3 hours for the code chunk below! (In principle it can be parallelised but it generated an error for me when I tried this with <code>parallel.method = cluster</code>.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>density<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">poly</span>(covid<span class="sc">$</span>density, <span class="dv">2</span>)[, <span class="dv">1</span>]</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>density<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">poly</span>(covid<span class="sc">$</span>density, <span class="dv">2</span>)[, <span class="dv">2</span>]</span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Do not run!</span></span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Took over 3 hours!</span></span>
<span id="cb110-5"><a href="#cb110-5" aria-hidden="true" tabindex="-1"></a><span class="co">#gwrmulti &lt;- gwr.multiscale(Rate ~ IMD + age0.11 + age25.34 + age50.59 + carebeds +</span></span>
<span id="cb110-6"><a href="#cb110-6" aria-hidden="true" tabindex="-1"></a><span class="co"># density.1 + density.2, data = covid_sp, adaptive = TRUE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To save time, the results are available below. The bandwidths do appear to vary.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="fu">url</span>(<span class="st">"https://github.com/profrichharris/profrichharris.github.io/raw/main/MandM/workspaces/gwrmulti.RData"</span>)</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(url)</span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a><span class="fu">close</span>(url)</span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a>gwrmulti</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ***********************************************************************
   *                       Package   GWmodel                             *
   ***********************************************************************
   Program starts at: 2022-08-21 14:44:09 
   Call:
   gwr.multiscale(formula = Rate ~ IMD + age0.11 + age25.34 + age50.59 + 
    carebeds + density.1 + density.2, data = covid_sp, adaptive = TRUE)

   Dependent (y) variable:  Rate
   Independent variables:  IMD age0.11 age25.34 age50.59 carebeds density.1 density.2
   Number of data points: 924
   ***********************************************************************
   *                       Multiscale (PSDM) GWR                          *
   ***********************************************************************

   *********************Model calibration information*********************
   Kernel function: bisquare 
   Adaptive bandwidths for each coefficient(number of nearest neighbours): 
              (Intercept) IMD age0.11 age25.34 age50.59 carebeds density.1
   Bandwidth           28 922      34      922      132      841       380
              density.2
   Bandwidth        186

   ****************Summary of GWR coefficient estimates:******************
                    Min.     1st Qu.      Median     3rd Qu.     Max.
   Intercept   40.390229  158.475456  197.569654  250.106703 341.7481
   IMD         -0.457266   -0.429212   -0.427347   -0.425449  -0.4210
   age0.11     -4.383024   -0.168031    3.233327    5.482906  15.0608
   age25.34     2.970842    2.980326    2.990406    2.999560   3.0909
   age50.59    -1.540099    3.976661    4.868116    6.199428  10.9802
   carebeds     0.041884    0.045506    0.050615    0.056445   0.0873
   density.1 -228.739192 -171.871215 -117.550561   -6.118907  67.3146
   density.2 -639.370049 -216.959473 -130.236970  -77.397916  26.1626
   ************************Diagnostic information*************************
   Number of data points: 924 
   Effective number of parameters (2trace(S) - trace(S'S)): 227.0379 
   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 696.9621 
   AICc value:  8395.1 
   AIC value:  8142.156 
   BIC value:  8216.88 
   Residual sum of squares:  301719.5 
   R-square value:  0.738389 
   Adjusted R-square value:  0.6530458 

   ***********************************************************************
   Program stops at: 2022-08-21 17:46:34 </code></pre>
</div>
</div>
</section>
<section id="geographically-and-temporally-weighted-regression" class="level3">
<h3 class="anchored" data-anchor-id="geographically-and-temporally-weighted-regression">Geographically and temporally weighted regression</h3>
<p>It also possible to add a time dimension and undertake geographically and temporally weighted regression in <code>GWmodel</code>. The following workspace loads monthly COVID-19 data for Manchester neighbourhoods.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="fu">url</span>(<span class="st">"https://github.com/profrichharris/profrichharris.github.io/raw/main/MandM/workspaces/manchester.RData"</span>)</span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(url)</span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a><span class="fu">close</span>(url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here are the monthly rates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(covid, <span class="fu">aes</span>(<span class="at">fill =</span> Rate )) <span class="sc">+</span></span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> month) <span class="sc">+</span></span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"RdBu"</span>) <span class="sc">+</span></span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>If now want to explore how the regression relationships vary in space-time then we can use the <code>bw.gtwr()</code> and <code>gtwr()</code> functions, for which we also need to specify a vector of time tags (<code>obs.tv = ...</code>). In these data, they are simply a numeric value, <code>covid$month_code</code> but see <code>?bw.gtwr()</code> and <code>?gtwr()</code> for further possibilities and for further information about the model.</p>
<p><img src="hazard.gif" class="img-fluid" width="75"></p>
<p><font size="3">The model will take a little time to run – enough time for you to get a cup of tea or coffee!</font></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>covid_sp <span class="ot">&lt;-</span> <span class="fu">as_Spatial</span>(covid)</span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>fml <span class="ot">&lt;-</span> <span class="fu">formula</span>(Rate <span class="sc">~</span> IMD <span class="sc">+</span> age0<span class="fl">.11</span> <span class="sc">+</span> age25<span class="fl">.34</span> <span class="sc">+</span> age50<span class="fl">.59</span> <span class="sc">+</span> carebeds <span class="sc">+</span> <span class="fu">poly</span>(density, <span class="dv">2</span>))</span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">&lt;-</span> <span class="fu">bw.gtwr</span>(fml, <span class="at">data =</span> covid_sp, <span class="at">obs.tv =</span> covid<span class="sc">$</span>month_code, <span class="at">adaptive =</span> <span class="cn">TRUE</span>)</span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>gtwrmod <span class="ot">&lt;-</span> <span class="fu">gtwr</span>(fml, <span class="at">data =</span> covid_sp, <span class="at">st.bw =</span> bw, <span class="at">obs.tv =</span> covid<span class="sc">$</span>month_code, <span class="at">adaptive =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here are the summary results of the model,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>gtwrmod</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ***********************************************************************
   *                       Package   GWmodel                             *
   ***********************************************************************
   Program starts at: 2022-08-21 09:11:51 
   Call:
   gtwr(formula = fml, data = covid_sp, obs.tv = covid$month_code, 
    st.bw = bw, adaptive = TRUE)

   Dependent (y) variable:  Rate
   Independent variables:  IMD age0.11 age25.34 age50.59 carebeds density
   Number of data points: 1768
   ***********************************************************************
   *                    Results of Global Regression                     *
   ***********************************************************************

   Call:
    lm(formula = formula, data = data)

   Residuals:
    Min      1Q  Median      3Q     Max 
-3.8388 -2.4526 -0.6694  0.8773 23.0668 

   Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)   
   (Intercept)        1.2277082  0.8772151   1.400  0.16182   
   IMD                0.0022343  0.0088457   0.253  0.80062   
   age0.11           -0.0311138  0.0307405  -1.012  0.31161   
   age25.34           0.0316351  0.0174764   1.810  0.07044 . 
   age50.59           0.1492102  0.0483997   3.083  0.00208 **
   carebeds           0.0009431  0.0014616   0.645  0.51886   
   poly(density, 2)1  8.4668105  5.2762201   1.605  0.10874   
   poly(density, 2)2 -5.6870143  3.6957704  -1.539  0.12404   

   ---Significance stars
   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
   Residual standard error: 3.542 on 1760 degrees of freedom
   Multiple R-squared: 0.007583
   Adjusted R-squared: 0.003636 
   F-statistic: 1.921 on 7 and 1760 DF,  p-value: 0.06261 
   ***Extra Diagnostic information
   Residual sum of squares: 22079.68
   Sigma(hat): 3.535908
   AIC:  9499.228
   AICc:  9499.331
   ***********************************************************************
   *    Results of Geographically and Temporally Weighted Regression     *
   ***********************************************************************

   *********************Model calibration information*********************
   Kernel function for geographically and temporally weighting: bisquare 
   Adaptive bandwidth for geographically and temporally  weighting: 606 (number of nearest neighbours)
   Regression points: the same locations as observations are used.
   Distance metric for geographically and temporally  weighting: A distance matrix is specified for this model calibration.

   ****************Summary of GTWR coefficient estimates:*****************
                              Min.       1st Qu.        Median       3rd Qu.
   Intercept          -7.467273452  -1.429007024  -0.431890521   0.188930147
   IMD                -0.060866478   0.000867536   0.006925644   0.016466529
   age0.11            -0.263923302  -0.041615611   0.007456504   0.032878161
   age25.34           -0.081155344   0.017377385   0.030977770   0.063555110
   age50.59           -0.284989530   0.110990723   0.159690984   0.238809884
   carebeds           -0.008797590   0.000070766   0.000863682   0.001820529
   poly(density, 2)1 -22.971393286   5.633766857  12.761674565  22.069777132
   poly(density, 2)2 -32.065614018  -8.663319026  -6.150064261  -3.539132987
                        Max.
   Intercept          6.5631
   IMD                0.0631
   age0.11            0.1432
   age25.34           0.2475
   age50.59           1.0677
   carebeds           0.0066
   poly(density, 2)1 94.7435
   poly(density, 2)2 38.3984
   ************************Diagnostic information*************************
   Number of data points: 1768 
   Effective number of parameters (2trace(S) - trace(S'S)): 57.81766 
   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 1710.182 
   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 9304.009 
   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 9247.793 
   Residual sum of squares: 18798.49 
   R-square value:  0.1550625 
   Adjusted R-square value:  0.1264803 

   ***********************************************************************
   Program stops at: 2022-08-21 09:13:00 </code></pre>
</div>
</div>
<p>They should be treated cautiously because the <code>Rate</code> value is strongly positively skewed such that it may have been better to have transformed it (e.g.&nbsp;taken its square root) prior to analysis. Even so, there is some evidence that the predictor <code>age0.11</code> variable, for example, varies spatially <em>and</em> temporally.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>covid<span class="sc">$</span>age0<span class="fl">.11</span>GWR <span class="ot">&lt;-</span> gtwrmod<span class="sc">$</span>SDF<span class="sc">$</span>age0<span class="fl">.11</span></span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a>covid<span class="sc">$</span>age0<span class="fl">.11</span>GWR[<span class="fu">abs</span>(gtwrmod<span class="sc">$</span>SDF<span class="sc">$</span>age0<span class="fl">.11</span>_TV) <span class="sc">&lt;</span> <span class="fl">1.96</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(covid, <span class="fu">aes</span>(<span class="at">fill =</span> age0<span class="fl">.11</span>GWR)) <span class="sc">+</span></span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>() <span class="sc">+</span></span>
<span id="cb118-5"><a href="#cb118-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> month) <span class="sc">+</span></span>
<span id="cb118-6"><a href="#cb118-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(<span class="st">"beta"</span>, <span class="at">mid =</span> <span class="st">"grey90"</span>, <span class="at">na.value =</span> <span class="st">"white"</span>, <span class="at">trans =</span> <span class="st">"reverse"</span>) <span class="sc">+</span></span>
<span id="cb118-7"><a href="#cb118-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb118-8"><a href="#cb118-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_colourbar</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="_spregress_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="generalised-gwr-models-with-poisson-and-binomial-options" class="level3">
<h3 class="anchored" data-anchor-id="generalised-gwr-models-with-poisson-and-binomial-options">Generalised GWR models with Poisson and Binomial options</h3>
<p>See <code>?ggwr.basic</code>.</p>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>In this session we have looked at spatial regression models as a way to address the problem of spatial autocorrelation in regression residuals and to allow for the possibility that regression relationships vary across a map. In presenting these methods, at least some could be taken as offering a ‘technical fix’ to the statistical issue of spatial dependencies in the data, violating assumptions of independence. Whilst that may be true, and the more spatial approaches can be used as diagnostic tools to check for a mis-specified model, notably one that lacks a critical explanatory variable or where the relationship between the X and Y variables is non-linear, the limitation of this thinking is that it treats geography as an error to be resolved and/or it rests on the belief that with sufficient information the geographical differences will be explained. What geographically weighted regression, for example, reminds us is that the nature of the relationship may be complex because it is changing in form across the study region as the socio-spatial causes also vary from place to place. Such spatial complexity may be challenging to accommodate within the parameters of conventional aspatial or spatially naïve statistical thinking but ignoring the geographical variation is not a solution. What spatial thinking brings to the table is the recognition of geographical context and the knowledge that geographically rooted social outcomes are not independent of where the processes giving rise to those outcomes are taking place.</p>
</section>
<section id="further-reading" class="level2">
<h2 class="anchored" data-anchor-id="further-reading">Further Reading</h2>
<p><img src="spatial_regression.jpg" class="img-fluid" width="100"></p>
<p><a href="https://uk.sagepub.com/en-gb/eur/spatial-regression-models/book262155" target="_blank">Spatial Regression Models (2nd edition) by MD Ward &amp; KS Gleditsch (2018)</a></p>
<p>Comber et al.&nbsp;(2022) A Route Map for Successful Applications of Geographically Weighted Regression. <a href="https://doi.org/10.1111/gean.12316" target="_blank">https://doi.org/10.1111/gean.12316</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>