---
title: "Follow-up exercise"
execute: 
  warning: false
  message: false
---

## To do

For this follow-up exercise, **create an R markdown file** that, when *knit*ted, includes the code and output for the following, ideally as a **pdf document**:

-   **To read the following file into R**: [https://github.com/profrichharris/profrichharris.github.io/raw/main/MandM/boundary%20files/Local_Authority.geojson](https://github.com/profrichharris/profrichharris.github.io/raw/main/MandM/boundary%20files/Local_Authority.geojson){target="_blank"}. The file is in .geojson format. The data are sourced from [here](https://data-communities.opendata.arcgis.com/search?q=IMD){target="_blank"} and give Index of Multiple Deprivation (IMD) data for English local authorities.
-  To create a neighbourhood list for the local authorities and then spatial weights. How you define neighbours is up to you.
-  To use the spatial weights to map clusters of high or low values of the variable `RAvgScor`. This is the rank of the average 2019 multiple deprivation score for each authority. (It isn't therefore, really a continuous variable^[it is ordinal] but we will treat it as though it is).

Conclude with a brief reflection on what, if anything, the map reveals about a possible geography of deprivation in England.

## To help

All that you need is in the session 'Measuring spatial autocorrelation'. Keep in mind that a rank with a low numeric value is high for deprivation (because 1 = most) so, rather confusingly perhaps, a cluster of high values is a cluster of low deprivation, and *vice versa*. Keep in mind, also, that some local authorities may not have any neighbours, depending upon how you define them, so you may need to change the `zero.policy` in some functions.
